services:
  postgres:
    image: postgres:16
    container_name: bankin-postgres
    environment:
      POSTGRES_USER: bankin
      POSTGRES_PASSWORD: bankin
      POSTGRES_DB: bankin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bankin-redis
    ports:
      - "6379:6379"

  rust-services:
    build:
      context: ./apps/rust-services
      dockerfile: Dockerfile
    container_name: bankin-rust
    ports:
      - "50051:50051"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: bankin-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://bankin:bankin@postgres:5432/bankin
      JWT_SECRET: une_cle_secrete_longue_et_complexe
      RUST_SERVICE_URL: rust-services:50051
    depends_on:
      - postgres
      - redis
      - rust-services

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: bankin-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data: