apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: bankin
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migrate
          image: ghcr.io/brsa-dev/bankin-api:latest
          command: ["node", "node_modules/.bin/prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bankin-secrets
                  key: DATABASE_URL
      restartPolicy: Never