apiVersion: v1
kind: Secret
metadata:
  name: bankin-secrets
  namespace: bankin
type: Opaque
stringData:
  DATABASE_URL: postgresql://bankin:bankin@postgres:5432/bankin
  JWT_SECRET: GcuLCKzVQ8rPswPSJe92nGNjNFeiBQIi5V8eJ7hIxy4